# Generated by Django 6.1.1 on 2026-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_library", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
