# Generated by Django 6.1.1 on 2026-10-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_library", "0002_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="digital_library.author"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="digital_library.genre"
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="books",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="shelves", to="digital_library.book"
            ),
        ),
    ]
