# Generated by Django 6.1.1 on 2026-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_library", "0003_alter_book_authors_alter_book_genres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelf",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="shelves", to="digital_library.book"
            ),
        ),
    ]
